{
    'name': 'SMS',
    'description': 'Student Management System',
    'sequence': -100,
    'version': '19.0.1.0.0',
    'summary': 'Manage student records and courses efficiently.',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': ['base', 'contacts', 'account', 'web_map'],
    'data': [
        'security/ir.model.access.csv',
        'views/course_views.xml',
        'views/subject_views.xml',
        'views/student_views.xml',
        'views/guardian_views.xml',
        'views/classroom_views.xml',
        'views/attendance_views.xml',
        'views/report_templates.xml',
        'views/student_report_views.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
}
